import { useState } from 'react'

// Icons
const ChevronDownIcon = () => (
  <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
    <path fillRule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clipRule="evenodd" />
  </svg>
)

const SendIcon = () => (
  <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
    <path d="M10.894 2.553a1 1 0 00-1.788 0l-7 14a1 1 0 001.169 1.409l5-1.429A1 1 0 009 15.571V11a1 1 0 112 0v4.571a1 1 0 00.725.962l5 1.428a1 1 0 001.17-1.408l-7-14z" />
  </svg>
)

// Sample FAQs
const faqs = [
  {
    question: "What is BuildPal?",
    answer: "BuildPal is an AI-powered platform that helps you build applications faster with intelligent code generation and pre-built templates."
  },
  {
    question: "How does the AI chat work?",
    answer: "Simply describe what you want to build in natural language, and our AI will generate code, suggest solutions, and guide you through the development process."
  },
  {
    question: "Is it free to use?",
    answer: "Yes! We offer a free tier that includes basic AI assistance and access to our template library. Premium plans are available for advanced features."
  },
  {
    question: "What programming languages are supported?",
    answer: "BuildPal supports JavaScript, TypeScript, React, Python, and many other popular languages and frameworks."
  },
  {
    question: "Can I export my code?",
    answer: "Absolutely! You own all the code generated by BuildPal and can export it at any time. No vendor lock-in."
  }
]

// Menu Component
const Menu = () => {
  return (
    <nav className="bg-white shadow-sm border-b border-gray-200">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center py-4">
          <div className="flex items-center">
            <h1 className="text-2xl font-bold bg-gradient-primary bg-clip-text text-transparent">
              BuildPal
            </h1>
          </div>
          <div className="hidden md:flex items-center space-x-8">
            <a href="#home" className="text-gray-600 hover:text-gray-900 transition-colors">Home</a>
            <a href="#chat" className="text-gray-600 hover:text-gray-900 transition-colors">AI Chat</a>
            <a href="#faq" className="text-gray-600 hover:text-gray-900 transition-colors">FAQ</a>
            <button className="bg-gradient-primary text-white px-4 py-2 rounded-full text-sm font-semibold hover:opacity-90 transition-opacity">
              Get Started
            </button>
          </div>
        </div>
      </div>
    </nav>
  )
}

// Hero Section Component
const HeroSection = () => {
  return (
    <section id="home" className="bg-white pt-20 pb-32">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center">
          <h1 className="text-5xl font-bold text-gray-900 mb-6">
            Build with AI
            <span className="block bg-gradient-primary bg-clip-text text-transparent">
              Code Faster Than Ever
            </span>
          </h1>
          <p className="text-2xl text-gray-600 mb-8 max-w-3xl mx-auto">
            Transform your ideas into production-ready code with our AI assistant.
            Just describe what you want to build, and watch the magic happen.
          </p>
          <a href="#chat" className="inline-block bg-gradient-primary text-white px-8 py-4 rounded-full text-lg font-semibold hover:opacity-90 transition-opacity shadow-lg">
            Start Building Now
          </a>
        </div>
      </div>
    </section>
  )
}

// Chat Section Component
const ChatSection = () => {
  const [message, setMessage] = useState('')
  const [messages, setMessages] = useState([
    {
      type: 'assistant',
      content: "Hello! I'm your AI development assistant. Tell me what you'd like to build and I'll help you get started!"
    }
  ])

  const handleSendMessage = (e) => {
    e.preventDefault()
    if (!message.trim()) return

    // Add user message
    const newMessages = [...messages, { type: 'user', content: message }]
    setMessages(newMessages)
    setMessage('')

    // Simulate AI response
    setTimeout(() => {
      const responses = [
        "That's a great idea! Let me help you break that down into smaller steps...",
        "I can definitely help you with that. Here's what I suggest we start with...",
        "Excellent! Let's create a plan for building that. First, we'll need to...",
        "Perfect! I'll guide you through building that step by step..."
      ]
      const randomResponse = responses[Math.floor(Math.random() * responses.length)]
      setMessages(prev => [...prev, { type: 'assistant', content: randomResponse }])
    }, 1000)
  }

  return (
    <section id="chat" className="bg-gray-50 py-20">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <h2 className="text-5xl font-bold text-gray-900 mb-4">
            AI Development Assistant
          </h2>
          <p className="text-2xl text-gray-600">
            Describe your idea and let our AI help you build it
          </p>
        </div>

        <div className="bg-white rounded-2xl shadow-lg p-6">
          {/* Chat Messages */}
          <div className="h-96 overflow-y-auto mb-6 space-y-4">
            {messages.map((msg, index) => (
              <div
                key={index}
                className={`flex ${msg.type === 'user' ? 'justify-end' : 'justify-start'}`}
              >
                <div
                  className={`max-w-xs lg:max-w-md px-4 py-2 rounded-2xl ${msg.type === 'user'
                      ? 'bg-gradient-primary text-white'
                      : 'bg-gray-100 text-gray-900'
                    }`}
                >
                  {msg.content}
                </div>
              </div>
            ))}
          </div>

          {/* Chat Input */}
          <form onSubmit={handleSendMessage} className="flex gap-3">
            <input
              type="text"
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              placeholder="Describe what you want to build..."
              className="flex-1 px-4 py-3 border border-gray-300 rounded-full focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
            />
            <button
              type="submit"
              className="bg-gradient-primary text-white p-3 rounded-full hover:opacity-90 transition-opacity"
            >
              <SendIcon />
            </button>
          </form>
        </div>
      </div>
    </section>
  )
}

// FAQ Component
const FAQ = () => {
  const [openFAQ, setOpenFAQ] = useState(null)

  const toggleFAQ = (index) => {
    setOpenFAQ(openFAQ === index ? null : index)
  }

  return (
    <section id="faq" className="bg-white py-20">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-5xl font-bold text-gray-900 mb-4">
            Frequently Asked Questions
          </h2>
          <p className="text-2xl text-gray-600">
            Everything you need to know about BuildPal
          </p>
        </div>
        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <div key={index} className="bg-gray-50 rounded-2xl">
              <button
                className="w-full text-left p-6 focus:outline-none"
                onClick={() => toggleFAQ(index)}
              >
                <div className="flex justify-between items-center">
                  <h3 className="text-xl font-semibold text-gray-900">{faq.question}</h3>
                  <ChevronDownIcon className={`transform transition-transform ${openFAQ === index ? 'rotate-180' : ''
                    }`} />
                </div>
              </button>
              {openFAQ === index && (
                <div className="px-6 pb-6">
                  <p className="text-gray-600">{faq.answer}</p>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}

// Bottom Section Component
const BottomSection = () => {
  return (
    <section className="bg-gray-900 text-white py-20">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <h2 className="text-4xl font-bold mb-4">
            Ready to Start Building?
          </h2>
          <p className="text-xl text-gray-300 mb-8">
            Join thousands of developers who are building faster with AI
          </p>
          <button className="bg-gradient-primary text-white px-8 py-4 rounded-full text-lg font-semibold hover:opacity-90 transition-opacity shadow-lg">
            Get Started Free
          </button>
        </div>

        <div className="border-t border-gray-800 pt-12">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div>
              <h3 className="text-2xl font-bold mb-4">BuildPal</h3>
              <p className="text-gray-400">
                AI-powered development platform for modern builders.
              </p>
            </div>
            <div>
              <h4 className="text-lg font-semibold mb-4">Product</h4>
              <ul className="space-y-2">
                <li><a href="#" className="text-gray-400 hover:text-white transition-colors">AI Chat</a></li>
                <li><a href="#" className="text-gray-400 hover:text-white transition-colors">Templates</a></li>
                <li><a href="#" className="text-gray-400 hover:text-white transition-colors">Documentation</a></li>
                <li><a href="#" className="text-gray-400 hover:text-white transition-colors">API</a></li>
              </ul>
            </div>
            <div>
              <h4 className="text-lg font-semibold mb-4">Support</h4>
              <ul className="space-y-2">
                <li><a href="#" className="text-gray-400 hover:text-white transition-colors">Help Center</a></li>
                <li><a href="#" className="text-gray-400 hover:text-white transition-colors">Community</a></li>
                <li><a href="#" className="text-gray-400 hover:text-white transition-colors">Contact</a></li>
                <li><a href="#" className="text-gray-400 hover:text-white transition-colors">Status</a></li>
              </ul>
            </div>
          </div>

          <div className="border-t border-gray-800 mt-12 pt-8 text-center">
            <p className="text-gray-400">&copy; 2025 BuildPal. All rights reserved.</p>
          </div>
        </div>
      </div>
    </section>
  )
}

// Main App Component
function App() {
  return (
    <div className="App">
      <Menu />
      <HeroSection />
      <ChatSection />
      <FAQ />
      <BottomSection />
    </div>
  )
}

export default App
